# Generated by Django 6.0.5 on 2026-05-18 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voiture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=50)),
                ('modele', models.CharField(max_length=50)),
                ('immatriculation', models.CharField(max_length=15, unique=True)),
                ('annee', models.IntegerField()),
                ('en_reparation', models.BooleanField(default=True)),
            ],
        ),
    ]
