# Generated by Django 6.0.5 on 2026-05-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recette',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recettes/'),
        ),
    ]
